# 產品模組範例 (P1 產品模組)
AI 簡報生成工具:
  description: "一款利用 AI 技術，只需輸入幾個關鍵字就能快速生成專業簡報的工具，主打省時高效，適用於企業級使用者。"
  prompt_fragment: "核心賣點為『極致省時』和『專業美觀』，必須突出其企業級的安全與穩定性。"
會員訂閱服務:
  description: "提供獨家內容、無廣告體驗和優先客服的月費制訂閱服務。"
  prompt_fragment: "核心賣點為『獨家』、『尊享』，強調成為社群一員的價值。"
